# docs/src/orchid/resources/config.yml
site:
  about:
    siteName: Moj
    siteDescription: This is a short description of this project.
Editorial:
  primaryColor: '#6666FF'
  legacySearch: false
  social:
    github: 'JeevanDeep/Obvious-task'
  metaComponents:
    - type: 'orchidSearch'
  menu:
    - type: 'separator'
      title: 'Wiki'
    - type: 'wiki'
    - type: 'page'
      itemId: 'Changelog'
    - type: 'separator'
      title: 'API Docs'
    - type: 'sourcedocPages'
      moduleType: 'kotlindoc'
      node: 'classes'
      asSubmenu: true
      submenuTitle: 'Classes'
    - type: 'sourcedocPages'
      moduleType: 'kotlindoc'
      node: 'packages'
      asSubmenu: true
      submenuTitle: 'Packages'
# config.yml
wiki:
  sections:
    userManual:
      adapter:
        type: "github"
        repo: "[jeevandeep/Obvious-task]"

# config.yml
services:
  publications:
    stages:
      - type: 'githubPages'
        username: '[jeevandeep]' # the username which created the personal access token
        repo: '[jeevandeep/Obvious-task]' # the repo to publish to