# docs/src/orchid/resources/config.yml
site:
  about:
    siteName: Moj
    siteDescription: This is a short description of this project.
Editorial:
  primaryColor: '#6666FF'
  legacySearch: false
  social:
    github: 'JeevanDeep/Obvious-task'
  metaComponents:
    - type: 'orchidSearch'
  menu:
    - type: 'separator'
      title: 'Wiki'
    - type: 'wiki'
    - type: 'page'
      itemId: 'Changelog'
    - type: 'separator'
      title: 'API Docs'
    - type: 'sourcedocPages'
      moduleType: 'kotlindoc'
      node: 'classes'
      asSubmenu: true
      submenuTitle: 'Classes'
    - type: 'sourcedocPages'
      moduleType: 'kotlindoc'
      node: 'packages'
      asSubmenu: true
      submenuTitle: 'Packages'

services:
  publications:
    stages:
      ghPages:
        branch: gh-pages
        repo: 'JeevanDeep/Obvious-task'
        username: 'JeevanDeep'